<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e3f25490-dcec-4b38-aed1-5ea1ea16ba96</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove=".info\Discrepancy\Past\**" />
    <EmbeddedResource Remove=".info\Discrepancy\Past\**" />
    <None Remove=".info\Discrepancy\Past\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include=".info\ApiRepos\LeafTesting\ForceUpdateTest.json" />
    <Content Include=".info\ApiRepos\LeafThreads.json" />
    <Content Include=".info\Discrepancy\Discrepancy.csv" />
    <Content Include=".info\Discrepancy\Discrepancy.sql" />
    <Content Include=".info\Discrepancy\LocalRepo\Discrepancy.json" />
    <Content Include=".info\MessageAnalysis\LocalRepo\CallRepo.json" />
    <Content Include=".info\MessageAnalysis\LocalRepo\CustomerRepo.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automate.Application\Automate.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.0" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".info\ApiRepos\LeafMessages.csv" />
    <None Include=".info\FormAnalysis\FormsToAnalyze.csv" />
    <None Include=".info\MessageAnalysis\PNContactForms.csv" />
    <None Include=".info\Reports\TextReport_LF.csv" />
    <None Include=".info\MessageAnalysis\MessageCallQuery.sql" />
    <None Include=".info\MessageAnalysis\MessagesToAnalyze.csv" />
    <None Include=".info\MessageAnalysis\MessageCustSubQuery.sql" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".info\FormAnalysis\LocalRepo\" />
    <Folder Include=".info\Reports\ContactUpdate\" />
  </ItemGroup>

</Project>
