using Automate.Domain.DiscrepancyAnalysis;
using Automate.Domain.ValueObjects;

namespace Automate.Domain.DiscrepancyTest;

public class NotesPatterns_Test
{
    #region Theory
    [
        Theory
        (Skip = "Skip this test unless you are improving the success rate")
        ,
        InlineData("ANSWERED BY: Paul||PROBLEM: mice||NOTES: The caller| a new customer| needed pest control service for mice.After getting the address| Paul informed her that they do not cover her area and suggested contacting Home Team Defense or Orkin instead.The caller thanked Paul and then ended the call.||CALLER: Karen Vecchi||NUMBER/S: (412) 607-6241||ADDRESS: 415 Edgewood Dr| Sarver| PA 16055||EMAIL: - -||* Upon checking the FOX Location Map| the provided address is within the service area.|", CallBillability.WrongArea),
        InlineData("ANSWERED BY: Ashton||PROBLEM: cockroaches||NOTES: The caller called back because he needed same-day pest control services for cockroaches.However| when asked for his zip code| he said he would call back later.The caller thanked Ashton and then hung up.||CALLER: - -||NUMBER/S: (407) 462-8184||ADDRESS: - -||EMAIL: - -|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY:  Alicia | |PROBLEM:  bees |  |NOTES: The caller| a new customer| needed service and quotes to treat bees which she is not able to identify so rep advised caller to be sure.Rep asked caller to reply to his text message if she is sure of the variety of bees she is having and then they will book the appointment.Caller agreed so she thanked the rep then hung up.||NAME:  Ellie        |  |PHONE:   (315) 481-2074||ADDRESS:   233 Duer St| Oswego| NY 13126| USA||EMAIL:   - -        ", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: IVR||NOTES: Caller hung up when no one picked up.||*Code red", CallBillability.MissedCall),
        InlineData("ANSWERED BY:  Jacob| |PROBLEM: hornets nest   |  |NOTES: The caller| a new customer| needed a one time service and quotes to get rid of a hornets nest which is right in his doorway.Rep said he will call him back since the connection is not good. ||NAME:  Noah Burton     |  |PHONE:   (603) 921-0080||ADDRESS:  - - ||EMAIL: - -          ", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Drew    | |PROBLEM:   fleas and ticks|  |NOTES: The caller| a new customer| needed service and quotes to treat fleas and ticks.After gathering more information about the problem| the rep recommended and explained their treatment services where they go out about 4 to 6 weeks and do the whole front and back yard from may to October as full treatments.Caller said he may have to call back so he thanked the rep then hung up.||NAME:  - -        |  |PHONE:   (817) 366-8801||ADDRESS:  Lubbock| TX 79410| USA||EMAIL: - -||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: IVR||NOTES: Caller hung up when no one picked up after more than 30 seconds.||", CallBillability.MissedCall),
        InlineData("ANSWERED BY:IVR||NOTES: Caller hung up when no one picked up after more than 30 seconds.||* Code red", CallBillability.MissedCall),
        InlineData("ANSWERED BY:  Jake||PROBLEM: black beetles||NOTES:  Caller| a new customer asked for black beetles control and wanted to know how to deal with those.Rep said they cannot just get rid of those for a one time treatment so he recommended a consistent service to treat the whole home.He was explaining the process but caller cut him off and then hung up.||NAME: Mina Lockas||PHONE: (817) 913-5068||ADDRESS:  Watauga| TX 76137| USA||EMAIL:   - -|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Casey||PROBLEM: carpenter ants||NOTES: The caller| a new customer| needed service and quotes to treat carpenter ants.After the address was given| rep apologized that they do not service his area so he recommended that he call Orkin.Caller thanked the rep then hung up.||NAME: Bill Nickel||PHONE: (724) 454-3217||ADDRESS: 115 Diner St| Darlington| PA 16115| USA||EMAIL: - -||* Outside of service area", CallBillability.WrongArea),
        InlineData("ANSWERED BY: Tim||PROBLEM: cicadas||NOTES: The caller needs a spray for cicadas.The rep recommended their Yard Enjoyment Plan.The rep will call her back in 5 minutes after he has done a little research on her pest issue.  ||NAME: Laura Waller||ADDRESS: Manteno IL 60950||PHONE: (815) 210-8244||EMAIL: --|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: IVR||PROBLEM: mice||NOTES: After hours.The caller is dealing with some mice in the basement.  She would like to request a call back.  ||NAME: Melody ||ADDRESS: Branford CT 06405||PHONE: (203) 506-8902||EMAIL: --||* code red", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Kennedy||PROBLEM: fleas||NOTES: The caller| a new customer| needed pest control service for fleas.After gathering information| Kennedy said that she would forward the details to her team and they would contact the caller as soon as they can.The caller thanked Kennedy and then hung up.||CALLER: Maria Merson||NUMBER/S: (407) 617-5305||ADDRESS: 3013 Eisenhower Rd| Highland Park| IL 60035||EMAIL: - -||* code green", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Casey||PROBLEM: bed bugs||NOTES: Caller| a new customer said she has bed bugs in her parents' home. Call described her problem so rep assured caller that they take care of those. Caller said she will have to ask her parents first and will call back to set an appointment. Caller thanked rep and hung up.||NAME: Cheryl||PHONE: (410) 336-2584||ADDRESS: Ocala| FL 34476| USA||EMAIL:  - -", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Jackson||PROBLEM: mice||NOTES: The caller| a new customer| needed pest control services for mice in a manufacturing office building.After obtaining the address| Jackson explained that an inspection was necessary for a commercial building.An appointment was scheduled for Thursday| May 23. The caller thanked Jackson and then hung up.||CALLER: Kathy Johansen (Liberty Engineering)||NUMBER/S: (617) 965-6644||ADDRESS: 26 Farwell St| Newton| MA 02460||EMAIL: acctspayable @libertyenginc.com|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Kevin||PROBLEM: carpenter bees||NOTES: The caller| a new customer| needed a quote for treating potential carpenter bees under the deck.After obtaining the address| Kevin asked the caller to take a picture of the bee and send it to him for identification.The caller agreed| thanked Kevin| and then hung up.||CALLER: Stanley Singleton||NUMBER/S: (773) 905-8966||ADDRESS: 3520 W 157th St| Markham| IL 60428||EMAIL: - -||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Jane||PROBLEM: yellow jackets||NOTES: The caller| a new customer| needed pest control services for yellow jackets for a gymnastic gym. After getting the address| Jane explained an inspection was necessary before they could provide a quote| to which the caller agreed. Jane said that she would follow up with the caller for the soonest available schedule for inspection. The caller thanked Jane and then hung up.||CALLER: Nick Sigalas||NUMBER/S: (516) 384-4242||ADDRESS: 425 Oser Ave| Hauppauge| NY 11788||EMAIL: nikosigas0@gmail.com||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY:   Bradley| |PROBLEM: hornets  |  |NOTES: The caller| a new customer| needed service and quotes to treat hornets.After gathering more information about the problem| the rep recommended and explained their consistent Home Protection Plan.This service includes all other pests without extra charge. Eventually| the caller agreed to move forward with the service so rep booked the appointment for Friday.Caller said she will call back to finalize the schedule. Caller thanked the rep then hung up.||NAME:  Elizabeth Rayfald     |  |PHONE:   (339) 222-6795||ADDRESS: 3955 East Ave| Rochester| NY 14618||EMAIL:  - -   ", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Evan| |PROBLEM: centipedes and ants  |  |NOTES: The caller| a new customer| needed service and quotes to treat centipedes and ants in her apartment unit.After gathering more information about the problem| the rep recommended an inspection which is free.Rep said the price varies as long as they remain consistent.Caller thanked the rep then hung up.||NAME:  Heaven Thompson        |  |PHONE: (815) 992-0582  ||ADDRESS:   1165 Stratford Dr W #2| Bourbonnais| IL 60914| USA||EMAIL:   - -        |", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Sean||PROBLEM: dust mites||NOTES: The caller| a new customer| needed one-time pest control services for dust mites in the apartment he is moving out of.After gathering information| an appointment for inspection was scheduled for Friday(May 24). The caller thanked Sean and then hung up.||CALLER: Cole Bush||NUMBER/S: (267) 884-5543||ADDRESS: 483 Medford St #2| Somerville| MA 02145||EMAIL: coleffbush@gmail.com||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Calder||PROBLEM: rats||NOTES: Caller| a new customer| asked for a same day service to get rid of rats in his home.He said he is in contract with another company treating their home.Owner of the home said they will have to call elsewhere.||NAME; - -||PHONE: (210) 492-7642||ADDRESS:  69 Pizarro Ave| Rancho Viejo| TX 78575| USA||EMAIL: - - |", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: IVR||NOTES: Caller hung up when no one picked up after more than 30 seconds.||* Code red", CallBillability.MissedCall),
        InlineData("ANSWERED BY:  IVR||NOTES:  Caller hung up when no one picked up after 30 seconds.||* code red", CallBillability.MissedCall),
        InlineData("ANSWERED BY: Drew    | |PROBLEM: ants or termites  |  |NOTES: The caller| a new customer| has either ants or termites so rep recommended a free inspection and said his technician will be giving the quote.Caller agreed so rep got caller's information and said he will call her back for the appointment. Caller thanked the rep then hung up.||NAME:    Lina Dean    |  |PHONE:   (917) 690-0483||ADDRESS: 114 Cantrell Ave| Middletown| NY 10940||EMAIL:   - -        |", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Kyla||PROBLEM: carpenter bees||NOTES: The caller| a new customer| needed same-day pest control services for carpenter bees in the fascia.After getting the address| Kyla stated that the soonest they could come out would be tomorrow.The caller said that she would call back. She thanked Kyla and then hung up.||CALLER: Sandy Johns||NUMBER/S: (315) 727-3607||ADDRESS: 3620 Melvin Dr S| Baldwinsville| NY 13027||EMAIL: - -", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: IVR||NOTES: Caller hung up when no one picked up after more than 30 seconds.| |", CallBillability.MissedCall),
        InlineData("ANSWERED BY: Michael||PROBLEM: carpenter bees||NOTES: The caller| a new customer| needed a carpenter bee removal service and mentioned he didn't want to kill them. Michael explained that they do not have a way to remove the bees without killing them. The caller thanked Michael and then hung up.||CALLER: - -||NUMBER/S: (917) 797-3985||ADDRESS: - -||EMAIL: - -|", CallBillability.Unknown),
        InlineData("ANSWERED BY: Carson||PROBLEM: honey bees| yellow jackets||NOTES: The caller| a new customer| needed pest control services for honey bees and yellow jackets.After getting the zip code| Carson explained that they could treat yellow jackets but couldn't treat honey bees because they are a protected species. He recommended contacting a local beekeeper first for assistance| and if she still had issues with yellow jackets| to call them back. The caller thanked Carson and then hung up.||CALLER: - -||NUMBER/S: (401) 952-8183||ADDRESS: Warwick| RI 02888||EMAIL: - -|", CallBillability.ServiceNotOffered),
        InlineData("NOTES: Call is in Spanish.|||Spanish Call||ANSWERED BY: Carson||NOTES: Caller asks the representative if he speaks Spanish.The representative doesn't| so he transfers the call over. Nobody else comes to assist the caller.||*Call came in during business hours from Google Ads for cockroaches.", CallBillability.Spanish),
        InlineData("ANSWERED BY: Adam||PROBLEM: bees||NOTES: The caller| a new customer| needed pest control services for bees in a commercial property(indoor playground). After gathering information| Adam said that he would follow up with the caller for the inspection schedule.The caller thanked Adam and then hung up. ||CALLER: Stephanie Bruce||NUMBER/S: (978) 606-3168||ADDRESS: 91 Mill St #3| Dracut| MA 01826||EMAIL: brucesa7@gmail.com", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Drew     | |PROBLEM:  bees |  |NOTES: The caller caller back to set the appointment after the call got disconnected earlier so the rep was scheduled for Monday.||NAME:   Deborah Alvarez       |  |PHONE:  (773) 255-8347 ||ADDRESS:  7630 W Myrtle Ave| Chicago| IL 60631| USA ||EMAIL:   debbiethemouse @comcat.net        |", CallBillability.RepeatCaller),
        InlineData("ANSWERED BY:  John||PROBLEM:  roaches||NOTES:  Caller| a new customer said she has problem with roaches but call got disconnected immediately|", CallBillability.HangUp),
        InlineData("ANSWERED BY: IVR||NOTES: The caller stayed on the line for more than 4 minutes before hanging up.  ||*Code red", CallBillability.MissedCall),
        InlineData("ANSWERED BY: inaudible||PROBLEM: bed bugs||NOTES: The caller| a new customer| needed same-day pest control services for bed bugs in his apartment.After getting the address| the rep informed him that same-day services are not available for bed bug treatment.The caller thanked the rep and then hung up.||CALLER: Angelo||NUMBER/S: (716) 398-8598||ADDRESS: 41 Tower St #422| Buffalo| NY 14215||EMAIL: - -|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY:   Ashton / Sean| |PROBLEM:   mice|  |NOTES: The caller| a new customer| asked for removal service of the dead rodents.After gathering more information about the problem| the rep recommended and tried to explain the plan however| caller said he will call back and dropped the call. ||NAME:  Christian         |  |PHONE:   (224) 600-0799||ADDRESS:   Prospect Heights| IL 60070| USA||EMAIL:   - -      ", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Brandon ||PROBLEM: bees||NOTES: The caller wanted to get a free estimate for a bee issue.The bees have overtaken a bird nest on her deck.The caller is not interested in pest control because she lives in a condo| she just wants to have the bee issue taken care of.The rep said that they will have to start with a free inspection.To confirm the type of bee they are dealing with| the caller will text over the picture to the rep and then ring back.  ||NAME: --||ADDRESS: Blackstone MA 01504||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: IVR||NOTES: Caller hung up when no one picked up after more than 30 seconds.||*code red", CallBillability.MissedCall),
        InlineData("ANSWERED BY:  Ernie||PROBLEM: pest control||NOTES: The caller is looking for a local pest control company.The rep said they have a Chicago North branch that could service his area.  The caller said he was not interested and hung up.  ||NAME: --||ADDRESS: Huntley IL 60142|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Mike||NOTES:  Caller asked for a Spanish speaking rep and Mike said there is no one available but then call got disconnected. ||*Code red", CallBillability.Spanish),
        InlineData("NOTES: Call is in Spanish.|||Spanish Call||NOTES: According to the conversation heard| the caller is looking for pricing for rats.The call ends without being answered by any staff member.", CallBillability.Spanish),
        InlineData("ANSWERED BY: Richard||PROBLEM: mice||NOTES: The caller| a new customer| needed pest control services for mice.After gathering information| Richard informed the caller that he would send the details to the team and someone would get in touch with her shortly.The caller thanked Richard and then hung up.||CALLER: Diane Deshiro||NUMBER/S: (781) 929-7189 / (781) 251-0110||ADDRESS: Dedham| MA 02026||EMAIL: - -|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Jordan    | |PROBLEM:  ants |  |NOTES: The caller| a new customer| needed service and quotes to treat ants which she specifically complained as carpenter ants.After gathering more information about the problem| the rep recommended and explained their Home Protection Plan quarterly treatments.With the discounts applied| rep quoted $ for the initial treatment and $ a month for the quarterly services.Caller will call back so she thanked the rep then hung up.||NAME:  - -       | |PHONE:   (860) 377-5906||ADDRESS:   Tolland| CT 06084| USA||EMAIL: - -          || ", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Fine  / Jacob  | |PROBLEM:  bees |  |NOTES: The caller| a new customer| needed a same day one time service and quotes to treat bees.After gathering more information about the problem| the rep recommended and explained their Home Protection Plan which is a quarterly treatment.Caller asked rep to call her back because of the bad connection. Caller thanked the rep then hung up.||NAME:  Jeannie        |  |PHONE:  (401) 556-1303 ||ADDRESS:   169 Buena Vista Dr| North Kingstown| RI 02852||EMAIL:    - -       ||* code green", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Brandon    | |PROBLEM:   carpenter bees|  |NOTES: The caller| a new customer| needed service and quotes to treat carpenter bees.After gathering more information about the problem| the rep recommended and explained their Home Protection Plan which is a quarterly service.Rep was about to give the prices but then call got disconnected. ||NAME:  John Kinne        |  |PHONE:  (413) 429-6605 ||ADDRESS: 20 Rockland St| Natick| MA 01760| USA||EMAIL:   - -        ||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Kaye||PROBLEM: lantern flies||NOTES: The caller| a new customer| needed pest control services for lantern flies for her neighbor's backyard. Kaye recommended giving their phone number to her neighbor to discuss services and pricing. The caller agreed| thanked Kaye| and then hung up.||CALLER: Lena Daniel||NUMBER/S: (516) 698-8725||ADDRESS: 260 Evelyn Rd| Mineola| NY 11501||EMAIL: - -||||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Ryan||PROBLEM: bed bugs||NOTES: The caller| a new customer| needed pest control services for bed bugs in an apartment.He mentioned that his roommate had caught a bed bug and stuck it to a piece of tape.After obtaining the zip code| Ryan recommended taking a picture of the bug and sending it for identification.However| the roommate preferred to bring the bug to the office. Ryan informed the caller that their office is located in Gurney.The caller thanked Ryan and then hung up.||CALLER: Robert Crook||NUMBER/S: (224) 290-7483||ADDRESS: Antioch| IL 60002||EMAIL: - -", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Michelle    | |PROBLEM:  bed bugs|  |NOTES: The caller| a new customer| wanted to get an inspection and service and quotes to treat possibly bed bugs in a multi-unit apartment building.The caller did not want to give any other information to the rep so they finally opted that the caller send a picture of the bug to the email and have them identify the pest for them to be able to do an inspection or treatment.Rep thanked the caller then hung up.||NAME:  - -        |  |PHONE:   (224) 436-4332||ADDRESS:   Old Mill Creek| IL 60002| USA||EMAIL:  - -         ", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY:  Jacob  | |PROBLEM: flies  |  |NOTES: The caller| a new customer| needed immediate service and quotes to treat flies.Rep said the soonest they may be able to go out would be next week. The rep recommended that they need to do consistent treatment to be able to take care of the problem.Rep recommended that caller reach out to Orkin if she wanted the soonest appointment.He said caller may call him if she wants to set up an appointment for the following week though. Caller thanked the rep then hung up.||NAME:  Donna Anderson       |  |PHONE:   (203) 912-3072||ADDRESS:    Montville| CT| USA||EMAIL:  - -         ", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Jeffrey||PROBLEM: Termites||NOTES: The caller| a new customer| wanted to have a termite inspection.The rep stated that they could do a free inspection| and then he explained the program in detail.The rep stated that he would simply call back once their dispatch team responded to him regarding his availability.||CALLER: HOWARD STEIER||NUMBER/S: (757) 297-1218||ADDRESS: 2425 Windward Shore Dr| Virginia Beach| VA 23451| USA||EMAIL: hsteier @aol.com", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Stephanie||PROBLEM: mice||NOTES: The caller| a new customer| needed pest control services for mice.After gathering information| Stephanie informed the caller that someone would call her back to assist her with the problem.The caller thanked Stephanie and then hung up.||CALLER: Jill Hyman||NUMBER/S: (954) 614-5835||ADDRESS: 2510 Manion Dr| Williamsburg| VA 23185||EMAIL: - -", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Harmony||PROBLEM: ground bees||NOTES: The caller wanted to get a quote for ground bee removal.Harmony said the reps are currently unavailable and she forwarded his information to the agents.Someone will call him back as soon as they are available.  ||NAME: --||ADDRESS: 06335||PHONE: (401) 595-5591||EMAIL: --||* code green", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Ashton ||PROBLEM: wasp nest removal||NOTES: The caller is looking for someone who could take down a wasp nest today.The rep transferred her to another agent.The rep said they will not be able to do a same-day service because of the holiday weekend.The caller thanked the rep and said she will reach back out if she does not find anything.  ||NAME: --||ADDRESS: 8126 Skystone Lp Manasas VA 20111||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY:  rep   | |PROBLEM:  bees |  |NOTES: The caller is a new customer and has called back to ask more questions about the service.After awhile| caller finally got into the service so rep set the account profile and booked the appointment for Tuesday afternoon. Caller thanked the rep then hung up.||NAME:  Trent Burkhalter| |PHONE:   (407) 489-2459||ADDRESS:   6119 Orange Cove Dr| Orlando| FL 32819| USA||EMAIL:  trentburk @hotmail.com|", CallBillability.RepeatCaller),
        InlineData("ANSWERED BY: John ||PROBLEM: yellow jackets||NOTES: The caller said they have yellow jackets and he is looking to get a same-day appointment.  The rep said they are booked up because of the holiday weekend.  The caller will keep looking for same-day treatment and will ring back if he does not find any.  ||NAME: John|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY:   John  | |PROBLEM:   wasps|  |NOTES: The caller| a new customer| needed same day service and quotes to treat wasps.Rep said the soonest they can go out would be on the 3rd of June and so caller thanked the rep then hung up.||NAME: Eric Young         |  |PHONE:   (917) 855-2868||ADDRESS:   2775 North St| Fairfield| CT 06824| USA||EMAIL:    - -       |", CallBillability.MarkedIncorrectly),
        InlineData("* Tech in neighborhood.||ANSWERED BY:  Parker||PROBLEM:  bees||NOTES:  Caller saw trucks in the neighborhood and wanted to get same day services for her sister who has bees however| rep apologized that the soonest they can go out would be on Tuesday of the following week.Caller thanked rep and ended the call.||NAME: - -||PHONE: (225) 279-9144||ADDRESS:  Zachary| LA 70791| USA", CallBillability.Referral),
        InlineData("ANSWERED BY: Paul    | |PROBLEM: wasps or underground bees|  |NOTES: The caller| a new customer| needed service and quotes to treat wasps or underground bees.Caller has further described her problem but placed the call on hold when her husband called.Rep said he will call her back. ||NAME: Barbara Esatto         |  |PHONE:   (516) 384-1247||ADDRESS:  76 Garrett Rd| Canton| CT 06019| USA||EMAIL:   - -        ||* code green", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY:  Brandon | |PROBLEM:   mice|  |NOTES: The caller| a new customer| needed service and quotes to treat mice.After gathering more information about the problem| the rep recommended and explained their Home Protection Plan.  ||NAME:  Maude Cassamajor        |  |PHONE: (781) 738-9583  ||ADDRESS: 910 Court St| Brockton| MA 02302| USA||EMAIL:   - -        |", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Jacob||PROBLEM: ground bees||NOTES: The caller| a new customer| needed pest control services for ground bees in the backyard. After getting the zip code| Jacob explained how the process works| what pests are covered| and the warranty. The caller stated that she is not interested in signing a contract. She thanked Jacob and then hung up. ||CALLER: Margaret Becker||NUMBER/S: (203) 848-5632||ADDRESS: Woodbridge| CT 06525||EMAIL: - -|", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: IVR||NOTES: The caller interacted with the IVR but hung up shortly after.||* Code red", CallBillability.MissedCall),
        InlineData("ANSWERED BY: Harmony||PROBLEM: roaches||NOTES: The caller| a new customer| needed a quote to treat roaches.After getting the zip code| Harmony said that someone would get in touch with him as soon as someone becomes available.The caller thanked Harmony and then hung up.||CALLER: - -||NUMBER/S: (860) 816-2181||ADDRESS: East Hartford| CT 06108||EMAIL: - -||", CallBillability.MarkedIncorrectly),
        InlineData("ANSWERED BY: Austin||PROBLEM: wasps nest||NOTES: The caller| a new customer| needed pest control services for a wasps nest located at the top of the garage.Austin explained the process and the warranty details.However| the caller was not interested in the recurring services| thanked Austin| and then hung up.||CALLER: - -||NUMBER/S: (847) 432-9377||ADDRESS: Highland Park| IL||EMAIL: - -||", CallBillability.MarkedIncorrectly),
        InlineData("NOTES: Call is in Spanish.|Spanish Call||ANSWERED BY: Masi||They don't treat food related businesses.||PROBLEM: Pest control||NOTES: Caller has a business. It's a butchery.They want to know the cost for fumigating.Representative tells him that they can't assist businesses that there have prepared food or sold. He suggests to call Orkin.||ADDRESS: Mission||Market: McAllen", CallBillability.Spanish),
        InlineData("|ANSWERED BY: Ben||PROBLEM: Mice||NOTES: The caller| a new customer| needs treatment for mice.The representative  explains their treatment plan.The customer prefers the no-kill method for mice..The caller thanks the rep and ends the call.|", CallBillability.ServiceNotOffered),
        InlineData("|ANSWERED BY: Alicia|PROBLEM: General pest control|NOTES: The caller| a new customer| needs treatment for general pest control.The caller is looking for a local company.The caller thanks the rep and ends the call.|NAME: Fred Harris||", CallBillability.Unknown),
        InlineData("ANSWERED BY: Kyle|||PROBLEM: Mice|||NOTES: The caller| a previous customer| needs treatment for mice.The representative explains their treatment plan. The caller has 1200 sq.ft.home.The representative says the initial treatment for an ongoing service costs $ 370| while the regular quarterly service is broken down to monthly payment of $ 70 each.The representative sets up the appointment for Friday between 8 AM and 5 PM.The caller thanks the rep and ends the call.|||NAME: Brianna Ferraro|||ADDRESS: 1509 Wellington Rd|||EMAIL: briannaferraro @mail.edilfi.edu", CallBillability.MarkedIncorrectly),
    ]
    #endregion
    public void NotesPatterns_ProperlyQualifiesNotesText(string note, CallBillability billability)
    {
        // Assemble and Act
        var result = NotesPatterns.MatchPatterns(note);
        var matches = result.MatchedPatterns;

        // Assert
        bool equality = billability != CallBillability.Unknown ? matches != string.Empty : matches == string.Empty;
        Assert.Equal(result.Billability, billability);
        Assert.True(equality);
    }

    #region Summary Theory
    [
        Theory,
        InlineData("Fox Pest Control offers a range of services for new and existing customers |  with a focus on protecting homes from pests like carpenter bees and spiders. The company is closed on national holidays and emphasizes the importance of quality service. With over 30 branches nationwide |  Fox Pest Control provides year-round support to keep homes safe and pest-free.", CallBillability.Unknown),
        InlineData("A customer named Sonny called Fox Pest Control to inquire about treating earwigs in his basement. The sales representative offered a home protection plan with quarterly services and unlimited visits in between. Sonny hesitated due to the monthly payment plan but eventually agreed to a one-year trial period and scheduled a service visit for the same day.", CallBillability.Billable),
        InlineData("Virginia called Fox Pest Control to inquire about services for dealing with a rat issue in her home. The sales representative |  Jacob |  provided information on pricing and services |  explaining the process of rodent elimination and maintenance. Virginia expressed interest in the service but wanted to gather more information before making a decision |  and Jacob offered to send her a text message with details for further consideration.", CallBillability.Billable),
        InlineData("Steven Skinner called Fox Pest Control to address an ant problem. The sales representative explained the treatment process |  pricing |  and scheduling options to Steven. They agreed on a monthly service plan and scheduled the first treatment for Wednesday morning |  with Steven providing his contact and payment information for the service agreement.", CallBillability.Billable),
        InlineData("A customer called Fox Pest Control to inquire about removing hornets from their property. The customer did not have services with Fox Pest Control but was considering switching from another pest company. The representative advised the customer to contact their current pest company first before scheduling service with Fox Pest Control.", CallBillability.Billable),
        InlineData("The conversation is a greeting from Fox Pest Control's Inside Sales team |  informing callers that their call may be recorded for quality purposes. The caller is prompted to indicate if they are calling to become a new customer of Fox Pest Control.", CallBillability.Unknown),
        InlineData("A frustrated customer in New York called Fox Pest Control about bed bugs in their apartment building |  expressing anger at the delayed response from the property management. The sales representative provided tips on managing the situation until professional treatment could be arranged |  including using alcohol wipes and washing bedding on high heat. The customer appreciated the advice and expressed gratitude before ending the call.", CallBillability.Unknown),
        InlineData("Ashley Gilberto called Fox Pest Control regarding an earwig issue in her home. The sales representative explained the service process |  pricing |  and scheduled an appointment for Friday. Ashley provided her email and agreed to sign the necessary documents for the service.", CallBillability.Billable),
        InlineData("A customer from Massachusetts called Fox Pest Control seeking a quote for spider removal. After providing their ZIP code and details |  they were transferred to a sales representative named Jacob who explained the service and pricing options. The customer |  Joshua |  expressed interest in the service and planned to follow up with Jacob for scheduling.", CallBillability.Billable),
        InlineData("A customer named Walter Jones called Fox Pest Control for help with rats and roaches. They discussed services and pricing |  and scheduled an appointment for Friday after the 4th of July. Walter provided his address and agreed to have his card on file for the appointment |  with the understanding that he wouldn't be charged until after the service visit.", CallBillability.Billable),
        InlineData("Sonia called Fox Pest Control for a free estimate regarding a bug issue in a cluttered room. The representative explained the treatment process |  pricing |  and the need to clear clutter for effective treatment. Sonia expressed the need to check her funds before committing and provided her contact information for follow-up.", CallBillability.Billable),
        InlineData("A customer named Lisa called Fox Pest Control to inquire about mosquito control services for her property. After discussing pricing and scheduling |  Lisa agreed to have the service done for four months this year. She provided her information |  completed the payment process |  and scheduled the appointment for the next day.", CallBillability.Billable),
        InlineData("A customer called Fox Pest Control to address a mouse issue in their pantry. The representative discussed treatment options |  costs |  and scheduling an appointment. The customer expressed concerns about the service agreement terms and ultimately opted for a 12-month commitment to address the mouse problem.", CallBillability.Billable),
        InlineData("Anthony called Fox Pest Control to inquire about pricing for killing and removing underground yellow jackets. He was transferred to the sales team and provided his information for scheduling. The sales representative explained the treatment options and pricing |  recommending a 90-day treatment cycle for a fixed price. Anthony decided to shop around and discuss the options with his partner before making a decision |  opting to receive a text quote for future reference.", CallBillability.Billable),
        InlineData("The caller requested the telephone number but did not provide a valid response |  prompting them to stay on the line to speak with a representative. The company provides information about their services |  customer portal |  and office hours on national holidays. The conversation ends with a reminder to stay on the line to speak with a representative and a note about the office closure on national holidays.", CallBillability.Unknown),
        //InlineData("The conversation is a phone greeting from Fox Pest Control's inside sales team. The caller is prompted to select options for becoming a new customer |  purchasing additional services |  or seeking customer service. The call may be recorded for quality purposes.", CallBillability),
        //InlineData("Jared Gill called Fox Pest Control to report getting rid of some pests |  but the call was cut off as it was after hours. The automated system prompted Jared to press different numbers for customer service or to purchase additional services. Jared was unable to complete his call due to the after-hours status of the company.", CallBillability),
        //InlineData("The conversation was an automated message from Fox Pest Control's inside sales team |  providing options for callers to select based on their needs |  such as becoming a new customer |  purchasing additional services |  or seeking customer service. The message also prompted callers to enter their ZIP code for appropriate routing and informed them that the call was received after hours |  advising them to call back during business hours or leave a voicemail.", CallBillability),
        //InlineData("The conversation was a recorded message from Fox Pest Control |  providing information on their services and holiday closures. They highlighted the behavior of carpenter bees and spiders |  offering custom protection plans. The message also mentioned opportunities to join the Fox family and directed callers to stay on the line to speak with a representative.", CallBillability),
        //InlineData("A customer from New York called Fox Pest Control to address a wasp nest issue under their deck. The sales representative offered a solution involving quarterly services to prevent future infestations. The customer agreed to a one-time service to remove the nest and scheduled an appointment for the same day.", CallBillability),
        //InlineData("Jordan called Fox Pest Control in Versailles |  Kentucky |  seeking help with mice in the attic. The sales representative |  Carson |  explained the rodent control process and pricing |  emphasizing the importance of consistency in treatments. Carson also reassured Jordan that the droppings are not harmful and offered to schedule a visit. Jordan decided to discuss the options with her husband and promised to call back |  ending the conversation with plans to follow up.", CallBillability),
        //InlineData("A customer called Fox Pest Control inquiring about eliminating silverfish. The sales representative |  Jacob |  explained the treatment process and pricing options |  emphasizing the need for consistent treatment to fully eradicate the pests. The customer |  Jean |  expressed concerns about ongoing monthly payments and requested more information before making a decision.", CallBillability),
        //InlineData("Regina called Fox Pest Control to inquire about a potential pest issue. After discussing the situation with the sales representative |  she learned it was an earwig problem. They discussed treatment options |  pricing |  and the environmentally friendly products used. Regina decided to consult with her husband before proceeding and was offered a quick appointment for the next day.", CallBillability),
        //InlineData("Jason called Fox Pest Control to inquire about ground bees in his backyard. The sales representative explained the treatment process and pricing for regular services |  which includes coverage for other pests as well. Jason expressed concerns about the cost and mentioned considering other options before ending the call with a promise to follow up if needed.", CallBillability),
        //InlineData("Susan called Fox Pest Control to request help with a wasp nest on her property in Mount Plymouth |  Florida. The representative explained the services and pricing |  but Susan expressed concerns about the size of her property and the affordability of monthly treatments. Ultimately |  Susan decided to explore other options and thanked the representative before ending the call.", CallBillability),
        //InlineData("Ashley called Fox Pest Control to inquire about dealing with potential murder hornets in her yard. The representative |  Ada |  gathered information and offered a quote for services |  explaining the treatment process and scheduling options. Ashley expressed concern about the safety of the treatment for pets and neighbors |  finalized the appointment for Friday |  and completed the payment process.", CallBillability),
        //InlineData("A customer called Fox Pest Control to report a potential nest of hornets or wasps underground. The representative discussed treatment options |  including identifying the type of pest and offering a home protection plan with a money-back guarantee. The customer was provided with pricing information and said they would discuss the options with their husband before making a decision.", CallBillability),
        //InlineData("A customer from Hicksville |  NY called Fox Pest Control to inquire about getting rid of house mice. The sales representative offered to transfer the call to an account manager for assistance. The customer |  named Shirley |  was provided with information on the service plan and pricing |  and expressed interest in discussing it further with her husband before making a decision.", CallBillability),
        //InlineData("A customer called Fox Pest Control to inquire about removing a yellow jacket nest in Pennsylvania. The sales representative explained the options of a single service or quarterly services with pricing details. The customer expressed interest in considering the options and thanked the representative before ending the call.", CallBillability),
        //InlineData("Donna called Fox Pest Control to inquire about services for her townhouse in Hampton |  New Jersey. She reported seeing ants and a mouse in her home and discussed pricing and service details with the representative |  Anthony. Donna mentioned needing to speak with her son before finalizing the service |  and agreed to call back on Friday to proceed.", CallBillability),
        //InlineData("A customer called Fox Pest Control looking for help with a bee issue |  but the company did not have a location near the customer's address in Kissimmee |  Florida. The customer was directed to the closest location in Orlando for assistance. The conversation ended with the customer thanking the representative and saying goodbye.", CallBillability),
        //InlineData("Olive called Fox Pest Control to request removal of a hornet's nest. The representative confirmed Olive's location |  explained the treatment process |  and provided pricing details. Olive agreed to the service |  signed the agreement |  and scheduled an appointment for the next day. Additional services like mosquito control and termite prevention were discussed but Olive declined for now.", CallBillability),
        //InlineData("A customer from Massachusetts calls Fox Pest Control to request a code for cockroach treatment at a property in Canton. The sales representative discusses the treatment plan |  pricing |  and recommends a year-long service to ensure the elimination of roaches. The customer agrees to discuss the proposal with their boss and will call back for confirmation.", CallBillability),
        //InlineData("A customer named Mary Anne called Fox Pest Control to inquire about removing wasps from her property in East Hampton. The representative |  Ryan |  explained the home protection plan |  pricing |  and services offered. Mary Anne agreed to a 12-month plan and scheduled an outdoor service for the same day. She provided payment information and signed the agreement through a secure process. Ryan ensured she had access to the customer portal for future interactions.", CallBillability),
        //InlineData("A customer from Hartford |  CT called Fox Pest Control with an issue of yellow jackets or hornets in their gutter. The sales representative explained the process of dealing with the pests and offered a yearly plan for comprehensive pest control services. The customer expressed interest in the plan and decided to call back after discussing with their husband.", CallBillability),
        //InlineData("A customer named New York called Fox Pest Control to request removal of a beehive on their garage. The representative |  Carl |  discussed the issue and offered solutions for both the beehive and ant problems. They agreed on a plan for quarterly treatments and potential ant control. New York mentioned needing to consult with their husband before finalizing the decision and agreed to follow up with Carl later.", CallBillability),
        //InlineData("Salina called Fox Pest Control to inquire about services for a bed bug issue in her home. She provided her address in Auburn |  New York |  and described the bed bug problem in her house. The representative discussed the service details |  pricing |  and scheduling an appointment for Monday afternoon. Salina had trouble receiving the bed bug education sheet via email but was advised on necessary preparations for the service. The representative sent a quote and instructed Salina to wash bedding on high heat and reduce clutter before the appointment. They agreed on payment terms and confirmed the appointment for Monday.", CallBillability),
        //InlineData("A customer called Fox Pest Control to report a rat sighting in their kitchen and requested immediate assistance. The sales representative |  Calder |  offered a customized treatment plan and discounted pricing for ongoing services. The customer |  Maheem |  agreed to the plan |  signed the agreement |  and scheduled a technician to visit their home that afternoon.", CallBillability),
        //InlineData("A customer named Florida called Fox Pest Control for a quote on pest control services for mice in their single-family home. The representative explained the service details |  pricing |  and scheduling for treatment. Florida requested to speak with their wife before committing and planned to call back within 5 minutes to confirm the service.", CallBillability),
        //InlineData("A customer called Fox Pest Control to inquire about the cost of removing a beehive. The representative gathered information about the location and nature of the nest |  explained the treatment process |  pricing |  and offered a discount. The customer expressed interest in scheduling the service for the following week and requested a callback to confirm.", CallBillability),
        //InlineData("A customer in Norfolk |  VA called Fox Pest Control to inquire about services for a European hornet nest. The representative explained pricing for a single service and a quarterly plan |  emphasizing the importance of ongoing treatments. The customer expressed financial concerns and agreed to follow up with the representative at a later time.", CallBillability),
        //InlineData("A customer called Fox Pest Control to inquire about services |  providing details about a duplex property. The conversation involved confirming contact information and email address for the customer. The call ended with the customer mentioning the name Angie and the representative saying Fox.", CallBillability),
        //InlineData("A customer called Fox Pest Control inquiring about bug spray pricing for a 2-bedroom apartment. The sales representative explained that for multi-unit buildings |  the property management or HOA needs to be involved. The customer was directed to contact their property management for assistance |  ending the call on a polite note.", CallBillability),
        //InlineData("The conversation was a brief exchange between a customer and a representative at Fox Pest Control |  with the customer confirming their identity and the representative acknowledging the information. The conversation seemed to involve discussing a customer named Damian and confirming details related to their account or services. The tone of the conversation was casual and focused on confirming information.", CallBillability),
        //InlineData("William called Fox Pest Control to inquire about treatment for a bed bug infestation in a family member's home. He asked about the steps needed to prepare for the treatment |  the duration of the service |  and the cost. The sales representative |  Carson |  provided information on the treatment process |  pricing |  and offered a payment plan option. They discussed the guarantee |  scheduling |  and exchanged contact information for further communication.", CallBillability),
        //InlineData("A customer called Fox Pest Control to inquire about removing a bee's nest under their porch. The customer |  New York |  expressed concern about not wanting to harm the bees and was directed to an account manager for assistance. The call concluded with New York providing their name and ZIP code for service verification before being transferred to an account manager.", CallBillability),
        //InlineData("A customer called Fox Pest Control to address yellow jacket nests near their mobile home. The representative |  Calder |  discussed treatment options and costs with the customer |  who expressed concerns about affordability and pet safety. They agreed on a plan for quarterly treatments over two years |  with discounts for senior citizens. The customer provided their information and agreed to the service |  scheduled for Friday |  while also discussing personal topics like donating plasma.", CallBillability),
        //InlineData("Clarence Lee called Fox Pest Control to inquire about removing a wasp or hornet nest from his garage in Vernon Hills. The sales representative |  Jameson |  explained the removal options and pricing |  offering a one-time service or a cost-efficient guaranteed program. Clarence mentioned discussing the decision with his wife and agreed to follow up with Jameson at a later time.", CallBillability),
        //InlineData("Mike called Fox Pest Control to inquire about yellow jacket removal. Ben explained the treatment process for dealing with yellow jackets that have nested inside the walls. They discussed the cost and service details |  and Mike decided to call back after considering his options.", CallBillability),
        //InlineData("Anthony called Fox Pest Control to inquire about pricing for wasp nest removal in his backyard. The sales representative explained the service process |  pricing |  and scheduling details to Anthony |  who mentioned needing to consult with his girlfriend due to their work schedules and pets. They agreed on the pricing and exchanged contact information for further communication.", CallBillability),
        //InlineData("A customer calls Fox Pest Control regarding mice and roaches issue. The sales representative gathers the customer's address and explains the service plan |  which includes quarterly visits to address the ongoing pest problem. The customer agrees to the service plan and the conversation ends with the customer acknowledging the terms.", CallBillability),
        //InlineData("Asher Marks called Fox Pest Control with an emergency regarding a hornet nest under the deck |  but was informed that the earliest appointment available was on Friday. The representative suggested contacting the Oregon branch for a quicker response to the situation. Asher thanked the representative and ended the call.", CallBillability),
        //InlineData("The conversation is an automated greeting from Fox Pest Control's inside sales team |  informing callers that their call may be recorded for quality purposes. Callers are given options to press 1 to become a new customer or press 2 for additional services. The message also mentions that the office will be closed on national holidays such as the 4th of July |  Thanksgiving |  Christmas Eve |  Christmas Day |  and New Year's Day.", CallBillability),
        //InlineData("A customer called Fox Pest Control after hours to inquire about hornet removal services. The customer provided their address and contact information |  and the sales representative assured them that the team would follow up promptly. The conversation ended with the customer thanking Fox Pest Control and saying goodbye.", CallBillability),
        //InlineData("A customer named Maysia called Fox Pest Control seeking help with a mouse infestation in her rented storage unit. She expressed frustration with the lack of assistance from the storage facility and insurance company. The sales representative promised to investigate the situation and get back to Maysia with potential solutions.", CallBillability),
        //InlineData("A customer from Bloomfield |  CT called Fox Pest Control to report bees congregating near their electrical outlet. The sales representative offered two service options |  with the customer leaning towards a one-time spray due to a loose outlet. The customer expressed interest in shopping around for other prices before making a decision.", CallBillability),
        //InlineData("The conversation was an automated greeting from Fox Pest Control's inside sales team |  offering options for new customers |  additional services |  or customer service. The call was then transferred to Josh |  who is ready to assist the caller with their specific needs.", CallBillability),
        //InlineData("A customer called Fox Pest Control to address a mouse or rat issue in their home. The sales representative discussed the service details |  pricing |  and scheduled a visit for the same day. The customer had difficulty making a payment over the phone but eventually succeeded. The sales representative explained the contract terms and assured a money-back guarantee.", CallBillability),
        //InlineData("The conversation was between a customer named Florida and a representative from Fox Pest Control named Primary. Florida inquired about pest control services for her home in Bellevue |  mentioning issues with ants and fleas. Primary explained the services offered |  pricing |  and discounts available. They discussed treating the yard for fleas and mosquitoes during the summer months. Florida agreed to the services and scheduled an appointment for Tuesday |  expressing satisfaction with the conversation.", CallBillability),
        //InlineData("A customer named Tim called Fox Pest Control to inquire about removing a wasp nest under his deck stairs. The sales representative discussed treatment options |  pricing |  and scheduling an appointment for Tim. They also explained the service agreement and sent Tim the necessary documents for review and signature. Ultimately |  Tim opted for a one-year service plan and confirmed the appointment for Monday morning.", CallBillability),
        //InlineData("A customer from Massachusetts called Fox Pest Control to inquire about removing a wasp nest in their house. The sales representative discussed treatment options |  pricing |  and the importance of ongoing service to prevent the wasps from returning. The customer expressed interest in starting with a one-time removal and considering a long-term plan if needed.", CallBillability),
        //InlineData("The conversation was between a customer named Pennsylvania and a representative from Fox Pest Control named Primary. Pennsylvania inquired about bed bug treatment pricing and methods |  expressing concerns about the infestation spreading from a neighboring apartment. Primary explained the treatment process |  pricing based on square footage |  and the importance of treating the entire building. Pennsylvania agreed to the treatment plan |  made a deposit |  and scheduled the service for the following Wednesday. They discussed preparation steps |  payment options |  and finalized the booking details.", CallBillability),
        //InlineData("A customer called Fox Pest Control inquiring about rat nest removal services. The sales representative explained the treatment plan |  pricing |  and scheduling options. The customer |  Julia |  expressed interest in the service and planned to discuss it with her husband before confirming the appointment. The sales representative |  Alicia |  guided Julia through the process of signing the service agreement and updating payment information for confirmation.", CallBillability),
        //InlineData("A customer called Fox Pest Control suspecting they had bed bugs and inquired about the cost of treatment. The sales representative explained the potential costs and suggested trying DIY products first. The customer expressed inability to afford professional services but appreciated the advice and mentioned potential interest in discounted services for disabled veterans.", CallBillability),
        //InlineData("A customer named Eileen from Massachusetts called Fox Pest Control seeking help with potential scorpion control. The customer provided their ZIP code |  03053 in Londonderry |  New Hampshire |  and the representative assured assistance. The conversation focused on addressing the customer's pest control needs in their service area.", CallBillability),
        //InlineData("A customer called Fox Pest Control inquiring about rat control services. The sales representative explained the treatment process |  frequency of visits |  and pricing details for a yearly contract. The customer expressed interest but mentioned they would compare quotes before making a decision |  thanking the representative for their time and ending the call.", CallBillability),
        //InlineData("Monica calls Fox Pest Control for a quote on bed bugs |  providing her name and ZIP code. She is transferred to an account specialist who explains the process and pricing for treating bed bugs in her apartment complex. The specialist advises Monica to contact her landlord first as they may cover the cost |  and offers to proceed with the service if approved.", CallBillability),
        //InlineData("A customer called Fox Pest Control about ground hornets in their patio area. The sales representative discussed the aggressive nature of the insects and offered a treatment plan. The customer expressed concern about the cost and ultimately decided not to proceed with the service.", CallBillability),
        //InlineData("A customer named Kaz called Fox Pest Control to inquire about a potential bed bug issue. The sales representative |  Kyle |  gathered information about the situation and scheduled a treatment for Monday. Kaz provided their email address and credit card information for the appointment. The conversation concluded with the confirmation of the appointment and Kaz expressing gratitude before ending the call.", CallBillability),
        //InlineData("The conversation was between a customer from Peoria |  IL |  and a representative from Fox Pest Control. The customer suspected they had bed bugs due to getting bitten and seeing unfamiliar items. The representative suggested an inspection and explained the treatment process |  eventually scheduling a visit to the customer's single-family home at 422 West Wilcox Avenue.", CallBillability),
        //InlineData("A customer from Windham |  New Hampshire called Fox Pest Control regarding a mice problem in their basement. The sales representative |  Carson |  discussed the treatment process |  pricing |  and reassured the customer about the use of traps instead of poison. They scheduled a service appointment and confirmed availability for weekdays between 8 AM to 5 PM.", CallBillability),
        //InlineData("A customer named David from Weymouth |  MA called Fox Pest Control to inquire about removing a wasp nest in his shed. Jenna transferred David to her colleague |  Drew |  who informed David that they were booked until next Wednesday or Thursday due to a busy season. David expressed his desire for a quicker removal |  but Drew assured him they could discuss services and pricing to accommodate his needs.", CallBillability),
        //InlineData("A customer named John called Fox Pest Control to address a mice issue in his residential home. The representative |  Anthony |  explained the service plan |  pricing |  and scheduling details to John |  who provided his information and agreed to the service. They discussed the increased rodent population in Massachusetts and finalized the appointment for Wednesday |  with John agreeing to the payment process and service terms.", CallBillability),
        //InlineData("Darlene called Fox Pest Control to address a carpenter ant issue in her home. The sales representative explained the treatment process |  costs |  and options for ongoing service. Darlene expressed interest in considering the service further and planned to follow up with the company.", CallBillability),
        //InlineData("James D'Abandanza called Fox Pest Control to address a flea problem at his home on Spring Street in York |  PA. The sales representative explained the service plan |  pricing |  and scheduled a visit for Wednesday evening. James opted for a one-year service plan and agreed to have his wife available during the appointment.", CallBillability),
        //InlineData("A customer in Washington |  DC called Fox Pest Control to inquire about same-day removal of a wasp nest due to a family member's severe allergy. The sales representative discussed pricing and services |  including coverage for various pests under their home protection plan. The customer expressed interest in potentially switching over to Fox Pest Control and requested quotes for both a one-time service and a plan.", CallBillability),
        //InlineData("A caller in Massachusetts contacted Fox Pest Control to inquire about removing wasp nests in their house. The representative gathered information about the issue and provided details on pricing and services. The caller was offered a discounted plan |  and arrangements were made for a technician to visit the same day.", CallBillability),
        //InlineData("Sahar called Fox Pest Control to address bug bites in her house. The sales representative offered a free inspection and discussed potential pest control options. Sahar opted for an inspection first and scheduled it for Wednesday morning.", CallBillability),
        //InlineData("A customer called Fox Pest Control to inquire about wasp and yellowjacket nest removal. They discussed service options |  pricing |  and scheduling for the removal. The customer agreed to a one-time service and provided payment information for the appointment on Monday.", CallBillability),
        //InlineData("A customer called Fox Pest Control to inquire about services for ants in their new home in Woodstock. They discussed treatment options and pricing |  and the customer agreed to a 24-month plan. The customer provided payment information and scheduled the initial treatment for the following Monday. The conversation concluded with the customer expressing gratitude and looking forward to the service.", CallBillability),
        //InlineData("A customer called Fox Pest Control with concerns about flying ants outside their house |  inquiring about immediate solutions for an upcoming party. The sales representative explained the company's services and offered to set up a subscription for future pest control needs. The customer decided to continue looking for assistance elsewhere |  ending the call with gratitude and farewells.", CallBillability),
        //InlineData("The conversation was between a representative from Fox Pest Control and a customer named Jota Valdez. They discussed setting up a service agreement and confirming contact information via email. The call ended with the customer agreeing to proceed and saying goodbye.", CallBillability),
        //InlineData("A customer calls Fox Pest Control and is guided through a phone menu before speaking with a representative named Maria. They discuss protecting the home from carpenter bees and finalize details for service on Baywood Drive in McAllen |  Texas. The call ends with the customer |  Texas |  saying goodbye.", CallBillability),
        //InlineData("The conversation was between a customer calling Fox Pest Control about a mouse problem in their home and an inside sales representative named Brandon. They discussed the mouse issue |  treatment procedures |  pricing |  scheduling a visit |  and payment details. The customer encountered some difficulties with signing the agreement and providing payment information but was assured that the technician would handle it during the visit. The call ended with the customer expressing gratitude and saying goodbye.", CallBillability),
    ]
    #endregion
    public void NotesPatterns_ProperlyQualifiesSummaryText(string summary, CallBillability billability)
    {
        // Assemble and Act
        var result = NotesPatterns.MatchPatterns(summary);
        var matches = result.MatchedPatterns;

        // Assert
        bool equality = billability != CallBillability.Unknown ? matches != string.Empty : matches == string.Empty;
        Assert.Equal(result.Billability, billability);
        Assert.True(equality);
    }
}
/*
 */