<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".info\LocalLogs.txt" />
    <None Include=".info\LocalLogs2.txt" />
    <None Include=".info\LocalLogs3.txt" />
  </ItemGroup>

</Project>
